pokedex=[]

file = open("/Users/bellou/Desktop/unt.txt", "r")

lines = file.readlines()

file.close()

for line in lines:
   a='/'+line.strip()
   pokedex.append(a)
print(pokedex)

megaliste=['/Deoxys Attaque','/Deoxys Défense','/Deoxys Vitesse','/Cheniselle Sable','/Cheniselle Déchet','/Shaymin Céleste','/Giratina Originel','/Motisma Chaleur','/Motisma Lavage','/Motisma Froid','/Motisma Hélice','/Motisma Tonte','/Morphéo Solaire','/Morphéo Pluie','/Morphéo Blizzard','/Bargantua Bleu','/Darumacho Transe','/Meloetta','/Boréas Totémique','/Fulguris Totémique','/Démétéros Totémique','/Kyurem Noir','/Kyurem Blanc','/Keldeo Décidé','/Mistigrix Femelle','/Exagide Assaut','/Pitrouille Mini','/Pitrouille Maxi','/Pitrouille Ultra','/Banshitrouye Mini','/Banshitrouye Maxi','/Banshitrouye Ultra','/Méga Florizarre','/Méga Dracaufeu X','/Méga Dracaufeu Y','/Méga Tortank','/Méga Alakazam','/Méga-Ectoplasma','/Méga Kangourex','/Méga Scarabrute','/Méga Léviator','/Méga Ptéra','/Méga Mewtwo X','/Méga Mewtwo Y','/Méga Pharamp','/Méga Cizayox','/Méga Scarhino','/Méga Démolosse','/Méga Tyranocif','/Méga Braségali','/Méga Gardevoir','/Méga Mysdibule','/Méga Galeking','/Méga Charmina','/Méga Elecsprint','/Méga Branette','/Méga Absol','/Méga Carchacrok','/Méga Lucario','/Méga Blizzaroi','/Floette Bleu','/Méga Latias','/Méga Latios','/Méga Nanméouïe','/Méga Steelix','/Méga Jungko','/Méga Laggron','/Méga Diancie','/Méga Gallame','/Méga Lockpin','/Méga Rayquaza','/Méga Métalosse','/Méga Drattak','/Méga Oniglali','/Méga Altaria','/Méga Camérupt','/Méga Sharpedo','/Méga Ténéfix','/Méga Flagadoss','/Méga Roucarnage','/Méga Dardargnan','/Primo Groudon','/Primo Kyogre','/Hoopa Déchaîné','/Arceus Feu','/Arceus Fée','/Arceus Spectre','/Arceus Dragon','/Arceus Electrik','/Arceus Combat','/Arceus Vol','/Arceus Insecte','/Arceus Plante','/Arceus Sol','/Arceus Eau','/Arceus Poison','/Arceus Psy','/Arceus Roche','/Arceus Acier','/Arceus Glace','/Arceus Ténèbres','/Pikachu Lady','/Pikachu Fighter','/Pikachu Docteur','/Pikachu Star','/Pikachu Rockeur','/Flabébé Bleu','/Flabébé Orange','/Flabébé Blanc','/Flabébé Jaune','/Floette Bleue','/Floette Oranges','/Floette Blanches','/Floette Jaunes','/Florges Bleue','/Florges Oranges','/Florges Blanches','/Florges Jaunes','/Sancoki Orient','/Tritosor Orient','/Amphinobi Sasha','/Plumeline Pom-Pom','/Plumeline Hula','/Plumeline Buyo','/Lougaroc Nocturne','/Froussardine Banc','/Météno Noyau Rouge','/Rattata Alola','/Rattatac Alola','/Raichu Alola','/Sabelette Alola','/Sablaireau Alola','/Goupix Alola','/Feunard Alola','/Taupiqueur Alola','/Triopiqueur Alola','/Miaouss Alola','/Persian Alola','/Racaillou Alola','/Gravalanch Alola','/Grolem Alola','/Grotadmorv Alola','/Noadkoko Alola','/Ossatueur Alola',"/Tadmorv Alola"]